[agent]
  interval = "10s"
  flush_interval = "10s"
  round_interval = true

# =========================
# NETFLOW (v9 + IPFIX compatible mode)
# =========================
[[inputs.netflow]]
  service_address = ":2055"

  # NetFlow v9 — основной и самый стабильный вариант
  protocol = "netflow v9"

  # буфер (полезно при нагрузке)
  read_buffer_size = "4MiB"

# =========================
# OUTPUT → VictoriaMetrics
# =========================
[[outputs.influxdb]]
  urls = ["http://victoriametrics:8428/write"]
  database = "netflow"
  timeout = "10s"
  skip_database_creation = true
  content_encoding = "identity"